# Generated by Django 2.2.3 on 2020-10-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SapId', models.CharField(max_length=18)),
                ('Hostname', models.CharField(max_length=14)),
                ('Loopback', models.GenericIPAddressField()),
                ('Macaddress', models.CharField(max_length=17)),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
